//*
// @file block.proto
// @brief Định nghĩa cấu trúc Khối (Block) trong YonaCode.
// @details Cấu trúc bao gồm:
//  - BlockHeader: Chứa ParentHash, StateRoot và PoW Nonce GPU-Centric.
//  - BlockBody: Chứa các giao dịch (có thể cắt tỉa sau 24h).
// Đây là đơn vị lưu trữ cơ bản của sổ cái phi tập trung.
//
// @author Vô Nhật Thiên (Khởi tạo)
// @date 2026-03-18

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: block/block.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tiêu đề khối (Block Header) - Lưu trữ vĩnh viễn
type BlockHeader struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Version        uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Height         uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	ParentHash     *Hash                  `protobuf:"bytes,3,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	StateRoot      *Hash                  `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"` // Gốc cây trạng thái (SMT)
	TxRoot         *Hash                  `protobuf:"bytes,5,opt,name=tx_root,json=txRoot,proto3" json:"tx_root,omitempty"`          // Gốc cây giao dịch (Merkle Tree)
	Timestamp      uint64                 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Difficulty     []byte                 `protobuf:"bytes,7,opt,name=difficulty,proto3" json:"difficulty,omitempty"`                                // Độ khó mục tiêu (256-bit U256)
	Nonce          uint64                 `protobuf:"fixed64,8,opt,name=nonce,proto3" json:"nonce,omitempty"`                                        // Đáp án PoW (Single Winner)
	MinerAddress   *Address               `protobuf:"bytes,9,opt,name=miner_address,json=minerAddress,proto3" json:"miner_address,omitempty"`        // Địa chỉ thợ đào nhận thưởng
	AbsoluteWeight []byte                 `protobuf:"bytes,10,opt,name=absolute_weight,json=absoluteWeight,proto3" json:"absolute_weight,omitempty"` // [BATCH 18] Tổng trọng số tích lũy (u128 - Fork Resolution)
	Manifesto      string                 `protobuf:"bytes,12,opt,name=manifesto,proto3" json:"manifesto,omitempty"`                                 // [V1.0.3-GENESIS] Tuyên ngôn GenZ (Ghi chú lịch sử)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlockHeader) Reset() {
	*x = BlockHeader{}
	mi := &file_block_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeader) ProtoMessage() {}

func (x *BlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_block_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeader.ProtoReflect.Descriptor instead.
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return file_block_block_proto_rawDescGZIP(), []int{0}
}

func (x *BlockHeader) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BlockHeader) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockHeader) GetParentHash() *Hash {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *BlockHeader) GetStateRoot() *Hash {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *BlockHeader) GetTxRoot() *Hash {
	if x != nil {
		return x.TxRoot
	}
	return nil
}

func (x *BlockHeader) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockHeader) GetDifficulty() []byte {
	if x != nil {
		return x.Difficulty
	}
	return nil
}

func (x *BlockHeader) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *BlockHeader) GetMinerAddress() *Address {
	if x != nil {
		return x.MinerAddress
	}
	return nil
}

func (x *BlockHeader) GetAbsoluteWeight() []byte {
	if x != nil {
		return x.AbsoluteWeight
	}
	return nil
}

func (x *BlockHeader) GetManifesto() string {
	if x != nil {
		return x.Manifesto
	}
	return ""
}

// Thân khối (Block Body) - Có thể bị cắt tỉa (Pruning) sau 24h
type BlockBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockBody) Reset() {
	*x = BlockBody{}
	mi := &file_block_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockBody) ProtoMessage() {}

func (x *BlockBody) ProtoReflect() protoreflect.Message {
	mi := &file_block_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockBody.ProtoReflect.Descriptor instead.
func (*BlockBody) Descriptor() ([]byte, []int) {
	return file_block_block_proto_rawDescGZIP(), []int{1}
}

func (x *BlockBody) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// Cấu trúc Khối đầy đủ
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *BlockHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body          *BlockBody             `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_block_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_block_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_block_block_proto_rawDescGZIP(), []int{2}
}

func (x *Block) GetHeader() *BlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetBody() *BlockBody {
	if x != nil {
		return x.Body
	}
	return nil
}

// [V1.0 FINAL] Cấu trúc Khối Rút gọn (Compact Block Propagation)
// Tối ưu hóa lan truyền mạng bằng việc lắp ráp khối tại chỗ (Local Reconstruction).
type CompactBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *BlockHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	CoinbaseTx    *Transaction           `protobuf:"bytes,2,opt,name=coinbase_tx,json=coinbaseTx,proto3" json:"coinbase_tx,omitempty"`   // Giao dịch thưởng luôn được gửi kèm
	ShortIds      []uint64               `protobuf:"varint,3,rep,packed,name=short_ids,json=shortIds,proto3" json:"short_ids,omitempty"` // Danh sách ID rút gọn của các tx khác trong Mempool
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactBlock) Reset() {
	*x = CompactBlock{}
	mi := &file_block_block_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactBlock) ProtoMessage() {}

func (x *CompactBlock) ProtoReflect() protoreflect.Message {
	mi := &file_block_block_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactBlock.ProtoReflect.Descriptor instead.
func (*CompactBlock) Descriptor() ([]byte, []int) {
	return file_block_block_proto_rawDescGZIP(), []int{3}
}

func (x *CompactBlock) GetHeader() *BlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CompactBlock) GetCoinbaseTx() *Transaction {
	if x != nil {
		return x.CoinbaseTx
	}
	return nil
}

func (x *CompactBlock) GetShortIds() []uint64 {
	if x != nil {
		return x.ShortIds
	}
	return nil
}

// Yêu cầu phần giao dịch thiếu hụt khi lắp ráp khối Compact
type GetBlockTxn struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BlockHash      []byte                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	MissingIndexes []uint32               `protobuf:"varint,2,rep,packed,name=missing_indexes,json=missingIndexes,proto3" json:"missing_indexes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetBlockTxn) Reset() {
	*x = GetBlockTxn{}
	mi := &file_block_block_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockTxn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockTxn) ProtoMessage() {}

func (x *GetBlockTxn) ProtoReflect() protoreflect.Message {
	mi := &file_block_block_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockTxn.ProtoReflect.Descriptor instead.
func (*GetBlockTxn) Descriptor() ([]byte, []int) {
	return file_block_block_proto_rawDescGZIP(), []int{4}
}

func (x *GetBlockTxn) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *GetBlockTxn) GetMissingIndexes() []uint32 {
	if x != nil {
		return x.MissingIndexes
	}
	return nil
}

// Phản hồi các giao dịch thiếu hụt cho Node nhận
type BlockTxn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockTxn) Reset() {
	*x = BlockTxn{}
	mi := &file_block_block_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockTxn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockTxn) ProtoMessage() {}

func (x *BlockTxn) ProtoReflect() protoreflect.Message {
	mi := &file_block_block_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockTxn.ProtoReflect.Descriptor instead.
func (*BlockTxn) Descriptor() ([]byte, []int) {
	return file_block_block_proto_rawDescGZIP(), []int{5}
}

func (x *BlockTxn) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_block_block_proto protoreflect.FileDescriptor

const file_block_block_proto_rawDesc = "" +
	"\n" +
	"\x11block/block.proto\x12\x0ebtc_genz.block\x1a\x13common/common.proto\x1a\x1dtransaction/transaction.proto\"\xd5\x03\n" +
	"\vBlockHeader\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x126\n" +
	"\vparent_hash\x18\x03 \x01(\v2\x15.btc_genz.common.HashR\n" +
	"parentHash\x124\n" +
	"\n" +
	"state_root\x18\x04 \x01(\v2\x15.btc_genz.common.HashR\tstateRoot\x12.\n" +
	"\atx_root\x18\x05 \x01(\v2\x15.btc_genz.common.HashR\x06txRoot\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\x12\x1e\n" +
	"\n" +
	"difficulty\x18\a \x01(\fR\n" +
	"difficulty\x12\x14\n" +
	"\x05nonce\x18\b \x01(\x06R\x05nonce\x12=\n" +
	"\rminer_address\x18\t \x01(\v2\x18.btc_genz.common.AddressR\fminerAddress\x12'\n" +
	"\x0fabsolute_weight\x18\n" +
	" \x01(\fR\x0eabsoluteWeight\x12\x1c\n" +
	"\tmanifesto\x18\f \x01(\tR\tmanifestoJ\x04\b\v\x10\fJ\x04\b\r\x10\x0eJ\x04\b\x0e\x10\x0fJ\x04\b\x0f\x10\x10J\x04\b\x10\x10\x11\"d\n" +
	"\tBlockBody\x12E\n" +
	"\ftransactions\x18\x01 \x03(\v2!.btc_genz.transaction.TransactionR\ftransactionsJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05\"k\n" +
	"\x05Block\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.btc_genz.block.BlockHeaderR\x06header\x12-\n" +
	"\x04body\x18\x02 \x01(\v2\x19.btc_genz.block.BlockBodyR\x04body\"\xa4\x01\n" +
	"\fCompactBlock\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.btc_genz.block.BlockHeaderR\x06header\x12B\n" +
	"\vcoinbase_tx\x18\x02 \x01(\v2!.btc_genz.transaction.TransactionR\n" +
	"coinbaseTx\x12\x1b\n" +
	"\tshort_ids\x18\x03 \x03(\x04R\bshortIds\"U\n" +
	"\vGetBlockTxn\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\fR\tblockHash\x12'\n" +
	"\x0fmissing_indexes\x18\x02 \x03(\rR\x0emissingIndexes\"Q\n" +
	"\bBlockTxn\x12E\n" +
	"\ftransactions\x18\x01 \x03(\v2!.btc_genz.transaction.TransactionR\ftransactionsB\x10Z\x0ebtc_genz/protob\x06proto3"

var (
	file_block_block_proto_rawDescOnce sync.Once
	file_block_block_proto_rawDescData []byte
)

func file_block_block_proto_rawDescGZIP() []byte {
	file_block_block_proto_rawDescOnce.Do(func() {
		file_block_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_block_proto_rawDesc), len(file_block_block_proto_rawDesc)))
	})
	return file_block_block_proto_rawDescData
}

var file_block_block_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_block_block_proto_goTypes = []any{
	(*BlockHeader)(nil),  // 0: btc_genz.block.BlockHeader
	(*BlockBody)(nil),    // 1: btc_genz.block.BlockBody
	(*Block)(nil),        // 2: btc_genz.block.Block
	(*CompactBlock)(nil), // 3: btc_genz.block.CompactBlock
	(*GetBlockTxn)(nil),  // 4: btc_genz.block.GetBlockTxn
	(*BlockTxn)(nil),     // 5: btc_genz.block.BlockTxn
	(*Hash)(nil),         // 6: btc_genz.common.Hash
	(*Address)(nil),      // 7: btc_genz.common.Address
	(*Transaction)(nil),  // 8: btc_genz.transaction.Transaction
}
var file_block_block_proto_depIdxs = []int32{
	6,  // 0: btc_genz.block.BlockHeader.parent_hash:type_name -> btc_genz.common.Hash
	6,  // 1: btc_genz.block.BlockHeader.state_root:type_name -> btc_genz.common.Hash
	6,  // 2: btc_genz.block.BlockHeader.tx_root:type_name -> btc_genz.common.Hash
	7,  // 3: btc_genz.block.BlockHeader.miner_address:type_name -> btc_genz.common.Address
	8,  // 4: btc_genz.block.BlockBody.transactions:type_name -> btc_genz.transaction.Transaction
	0,  // 5: btc_genz.block.Block.header:type_name -> btc_genz.block.BlockHeader
	1,  // 6: btc_genz.block.Block.body:type_name -> btc_genz.block.BlockBody
	0,  // 7: btc_genz.block.CompactBlock.header:type_name -> btc_genz.block.BlockHeader
	8,  // 8: btc_genz.block.CompactBlock.coinbase_tx:type_name -> btc_genz.transaction.Transaction
	8,  // 9: btc_genz.block.BlockTxn.transactions:type_name -> btc_genz.transaction.Transaction
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_block_block_proto_init() }
func file_block_block_proto_init() {
	if File_block_block_proto != nil {
		return
	}
	file_common_common_proto_init()
	file_transaction_transaction_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_block_proto_rawDesc), len(file_block_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_block_proto_goTypes,
		DependencyIndexes: file_block_block_proto_depIdxs,
		MessageInfos:      file_block_block_proto_msgTypes,
	}.Build()
	File_block_block_proto = out.File
	file_block_block_proto_goTypes = nil
	file_block_block_proto_depIdxs = nil
}
