//*
// @file consensus.proto
// @brief Định nghĩa các tham số đồng thuận và cấu hình mạng lưới BTC GenZ.
// @details Chứa các hằng số về thời gian khối, phần thưởng, và các quy tắc khóa (Lock-up).
//
// @author Vô Nhật Thiên (Khởi tạo)
// @date 2026-03-18

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: consensus/consensus.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncInstruction_Strategy int32

const (
	SyncInstruction_CONTINUE      SyncInstruction_Strategy = 0 // Tiếp tục tải khối tiếp theo
	SyncInstruction_BACKTRACK     SyncInstruction_Strategy = 1 // Lùi lại để tìm điểm chung (Healing)
	SyncInstruction_STALL         SyncInstruction_Strategy = 2 // Tạm dừng (Chờ Peer hoặc trạng thái khác)
	SyncInstruction_DEEP_RECOVERY SyncInstruction_Strategy = 3 // Lỗi nghiêm trọng, cần xóa đệm và làm mới
)

// Enum value maps for SyncInstruction_Strategy.
var (
	SyncInstruction_Strategy_name = map[int32]string{
		0: "CONTINUE",
		1: "BACKTRACK",
		2: "STALL",
		3: "DEEP_RECOVERY",
	}
	SyncInstruction_Strategy_value = map[string]int32{
		"CONTINUE":      0,
		"BACKTRACK":     1,
		"STALL":         2,
		"DEEP_RECOVERY": 3,
	}
)

func (x SyncInstruction_Strategy) Enum() *SyncInstruction_Strategy {
	p := new(SyncInstruction_Strategy)
	*p = x
	return p
}

func (x SyncInstruction_Strategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncInstruction_Strategy) Descriptor() protoreflect.EnumDescriptor {
	return file_consensus_consensus_proto_enumTypes[0].Descriptor()
}

func (SyncInstruction_Strategy) Type() protoreflect.EnumType {
	return &file_consensus_consensus_proto_enumTypes[0]
}

func (x SyncInstruction_Strategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncInstruction_Strategy.Descriptor instead.
func (SyncInstruction_Strategy) EnumDescriptor() ([]byte, []int) {
	return file_consensus_consensus_proto_rawDescGZIP(), []int{5, 0}
}

type SyncChainResponse_Status int32

const (
	SyncChainResponse_ACCEPTED       SyncChainResponse_Status = 0
	SyncChainResponse_REORG_SUCCESS  SyncChainResponse_Status = 1
	SyncChainResponse_INVALID_CHAIN  SyncChainResponse_Status = 2
	SyncChainResponse_ORPHAN         SyncChainResponse_Status = 3
	SyncChainResponse_INTERNAL_ERROR SyncChainResponse_Status = 4 // [VANGUARD-FIX] Thêm mã trạng thái cho Lỗi Cục Bộ (DB hỏng/bad sector)
)

// Enum value maps for SyncChainResponse_Status.
var (
	SyncChainResponse_Status_name = map[int32]string{
		0: "ACCEPTED",
		1: "REORG_SUCCESS",
		2: "INVALID_CHAIN",
		3: "ORPHAN",
		4: "INTERNAL_ERROR",
	}
	SyncChainResponse_Status_value = map[string]int32{
		"ACCEPTED":       0,
		"REORG_SUCCESS":  1,
		"INVALID_CHAIN":  2,
		"ORPHAN":         3,
		"INTERNAL_ERROR": 4,
	}
)

func (x SyncChainResponse_Status) Enum() *SyncChainResponse_Status {
	p := new(SyncChainResponse_Status)
	*p = x
	return p
}

func (x SyncChainResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncChainResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_consensus_consensus_proto_enumTypes[1].Descriptor()
}

func (SyncChainResponse_Status) Type() protoreflect.EnumType {
	return &file_consensus_consensus_proto_enumTypes[1]
}

func (x SyncChainResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncChainResponse_Status.Descriptor instead.
func (SyncChainResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_consensus_consensus_proto_rawDescGZIP(), []int{6, 0}
}

// Cấu hình tham số đồng thuận
type ConsensusParams struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	TargetBlockTime              uint32                 `protobuf:"varint,1,opt,name=target_block_time,json=targetBlockTime,proto3" json:"target_block_time,omitempty"`
	DifficultyAdjustmentInterval uint32                 `protobuf:"varint,2,opt,name=difficulty_adjustment_interval,json=difficultyAdjustmentInterval,proto3" json:"difficulty_adjustment_interval,omitempty"`
	RewardLockupPeriod           uint32                 `protobuf:"varint,3,opt,name=reward_lockup_period,json=rewardLockupPeriod,proto3" json:"reward_lockup_period,omitempty"`
	MempoolNanoResetInterval     uint32                 `protobuf:"varint,4,opt,name=mempool_nano_reset_interval,json=mempoolNanoResetInterval,proto3" json:"mempool_nano_reset_interval,omitempty"`
	MaxBlockSize                 uint32                 `protobuf:"varint,5,opt,name=max_block_size,json=maxBlockSize,proto3" json:"max_block_size,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ConsensusParams) Reset() {
	*x = ConsensusParams{}
	mi := &file_consensus_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusParams) ProtoMessage() {}

func (x *ConsensusParams) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusParams.ProtoReflect.Descriptor instead.
func (*ConsensusParams) Descriptor() ([]byte, []int) {
	return file_consensus_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *ConsensusParams) GetTargetBlockTime() uint32 {
	if x != nil {
		return x.TargetBlockTime
	}
	return 0
}

func (x *ConsensusParams) GetDifficultyAdjustmentInterval() uint32 {
	if x != nil {
		return x.DifficultyAdjustmentInterval
	}
	return 0
}

func (x *ConsensusParams) GetRewardLockupPeriod() uint32 {
	if x != nil {
		return x.RewardLockupPeriod
	}
	return 0
}

func (x *ConsensusParams) GetMempoolNanoResetInterval() uint32 {
	if x != nil {
		return x.MempoolNanoResetInterval
	}
	return 0
}

func (x *ConsensusParams) GetMaxBlockSize() uint32 {
	if x != nil {
		return x.MaxBlockSize
	}
	return 0
}

// [ENGINE API V2] Nhiệm vụ khai thác (Black Box)
// Go gửi gói này sang Rust để bắt đầu băm mà không cần callback
type MiningTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *BlockHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Threads       uint32                 `protobuf:"varint,2,opt,name=threads,proto3" json:"threads,omitempty"`
	Intensity     uint32                 `protobuf:"varint,3,opt,name=intensity,proto3" json:"intensity,omitempty"`                  // 0-100
	SessionId     uint64                 `protobuf:"varint,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // [V5.3] Nhận diện phiên từ Go
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiningTask) Reset() {
	*x = MiningTask{}
	mi := &file_consensus_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiningTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiningTask) ProtoMessage() {}

func (x *MiningTask) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiningTask.ProtoReflect.Descriptor instead.
func (*MiningTask) Descriptor() ([]byte, []int) {
	return file_consensus_consensus_proto_rawDescGZIP(), []int{1}
}

func (x *MiningTask) GetHeader() *BlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MiningTask) GetThreads() uint32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *MiningTask) GetIntensity() uint32 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

func (x *MiningTask) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

// [ENGINE API V2] Kết quả khai thác
type MiningResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	SessionId     uint64                 `protobuf:"varint,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // [V5.3] Gắn thẻ phiên để tránh "râu ông nọ cắm cằm bà kia"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiningResult) Reset() {
	*x = MiningResult{}
	mi := &file_consensus_consensus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiningResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiningResult) ProtoMessage() {}

func (x *MiningResult) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_consensus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiningResult.ProtoReflect.Descriptor instead.
func (*MiningResult) Descriptor() ([]byte, []int) {
	return file_consensus_consensus_proto_rawDescGZIP(), []int{2}
}

func (x *MiningResult) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *MiningResult) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *MiningResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MiningResult) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type BlockExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockBodyRaw  []byte                 `protobuf:"bytes,1,opt,name=block_body_raw,json=blockBodyRaw,proto3" json:"block_body_raw,omitempty"`
	MinerAddress  []byte                 `protobuf:"bytes,2,opt,name=miner_address,json=minerAddress,proto3" json:"miner_address,omitempty"`
	Height        uint64                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Nonce         uint64                 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockExecutionRequest) Reset() {
	*x = BlockExecutionRequest{}
	mi := &file_consensus_consensus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockExecutionRequest) ProtoMessage() {}

func (x *BlockExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_consensus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockExecutionRequest.ProtoReflect.Descriptor instead.
func (*BlockExecutionRequest) Descriptor() ([]byte, []int) {
	return file_consensus_consensus_proto_rawDescGZIP(), []int{3}
}

func (x *BlockExecutionRequest) GetBlockBodyRaw() []byte {
	if x != nil {
		return x.BlockBodyRaw
	}
	return nil
}

func (x *BlockExecutionRequest) GetMinerAddress() []byte {
	if x != nil {
		return x.MinerAddress
	}
	return nil
}

func (x *BlockExecutionRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockExecutionRequest) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

// [SYNC-V4] Giao thức đồng bộ tập trung tại Rust Core
type SyncChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlocksRaw     [][]byte               `protobuf:"bytes,1,rep,name=blocks_raw,json=blocksRaw,proto3" json:"blocks_raw,omitempty"` // Danh sách các khối liên tiếp nhận được từ mạng
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncChainRequest) Reset() {
	*x = SyncChainRequest{}
	mi := &file_consensus_consensus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncChainRequest) ProtoMessage() {}

func (x *SyncChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_consensus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncChainRequest.ProtoReflect.Descriptor instead.
func (*SyncChainRequest) Descriptor() ([]byte, []int) {
	return file_consensus_consensus_proto_rawDescGZIP(), []int{4}
}

func (x *SyncChainRequest) GetBlocksRaw() [][]byte {
	if x != nil {
		return x.BlocksRaw
	}
	return nil
}

type SyncInstruction struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Strategy      SyncInstruction_Strategy `protobuf:"varint,1,opt,name=strategy,proto3,enum=btc_genz.consensus.SyncInstruction_Strategy" json:"strategy,omitempty"`
	StartHeight   uint64                   `protobuf:"varint,2,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"` // Cao độ bắt đầu tải (nếu lùi)
	EndHeight     uint64                   `protobuf:"varint,3,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`       // Cao độ kết thúc tải
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncInstruction) Reset() {
	*x = SyncInstruction{}
	mi := &file_consensus_consensus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInstruction) ProtoMessage() {}

func (x *SyncInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_consensus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInstruction.ProtoReflect.Descriptor instead.
func (*SyncInstruction) Descriptor() ([]byte, []int) {
	return file_consensus_consensus_proto_rawDescGZIP(), []int{5}
}

func (x *SyncInstruction) GetStrategy() SyncInstruction_Strategy {
	if x != nil {
		return x.Strategy
	}
	return SyncInstruction_CONTINUE
}

func (x *SyncInstruction) GetStartHeight() uint64 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

func (x *SyncInstruction) GetEndHeight() uint64 {
	if x != nil {
		return x.EndHeight
	}
	return 0
}

type SyncChainResponse struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	Status            SyncChainResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=btc_genz.consensus.SyncChainResponse_Status" json:"status,omitempty"`
	NewHeight         uint64                   `protobuf:"varint,2,opt,name=new_height,json=newHeight,proto3" json:"new_height,omitempty"`
	ForkPoint         uint64                   `protobuf:"varint,3,opt,name=fork_point,json=forkPoint,proto3" json:"fork_point,omitempty"`
	OrphanedTxHashes  [][]byte                 `protobuf:"bytes,4,rep,name=orphaned_tx_hashes,json=orphanedTxHashes,proto3" json:"orphaned_tx_hashes,omitempty"` // Các giao dịch cần trả lại Mempool
	OrphanedTxsRaw    [][]byte                 `protobuf:"bytes,6,rep,name=orphaned_txs_raw,json=orphanedTxsRaw,proto3" json:"orphaned_txs_raw,omitempty"`       // Dữ liệu thô để nạp lại Mempool
	ErrorMsg          string                   `protobuf:"bytes,5,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	MissingParentHash string                   `protobuf:"bytes,7,opt,name=missing_parent_hash,json=missingParentHash,proto3" json:"missing_parent_hash,omitempty"` // [VANGUARD-ORPHAN] Mã băm của khối cha bị thiếu để Go đi tìm
	Instruction       *SyncInstruction         `protobuf:"bytes,8,opt,name=instruction,proto3" json:"instruction,omitempty"`                                        // [VANGUARD-COMMAND] Lệnh chiến thuật từ Rust Core
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncChainResponse) Reset() {
	*x = SyncChainResponse{}
	mi := &file_consensus_consensus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncChainResponse) ProtoMessage() {}

func (x *SyncChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_consensus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncChainResponse.ProtoReflect.Descriptor instead.
func (*SyncChainResponse) Descriptor() ([]byte, []int) {
	return file_consensus_consensus_proto_rawDescGZIP(), []int{6}
}

func (x *SyncChainResponse) GetStatus() SyncChainResponse_Status {
	if x != nil {
		return x.Status
	}
	return SyncChainResponse_ACCEPTED
}

func (x *SyncChainResponse) GetNewHeight() uint64 {
	if x != nil {
		return x.NewHeight
	}
	return 0
}

func (x *SyncChainResponse) GetForkPoint() uint64 {
	if x != nil {
		return x.ForkPoint
	}
	return 0
}

func (x *SyncChainResponse) GetOrphanedTxHashes() [][]byte {
	if x != nil {
		return x.OrphanedTxHashes
	}
	return nil
}

func (x *SyncChainResponse) GetOrphanedTxsRaw() [][]byte {
	if x != nil {
		return x.OrphanedTxsRaw
	}
	return nil
}

func (x *SyncChainResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *SyncChainResponse) GetMissingParentHash() string {
	if x != nil {
		return x.MissingParentHash
	}
	return ""
}

func (x *SyncChainResponse) GetInstruction() *SyncInstruction {
	if x != nil {
		return x.Instruction
	}
	return nil
}

var File_consensus_consensus_proto protoreflect.FileDescriptor

const file_consensus_consensus_proto_rawDesc = "" +
	"\n" +
	"\x19consensus/consensus.proto\x12\x12btc_genz.consensus\x1a\x11block/block.proto\"\xa0\x02\n" +
	"\x0fConsensusParams\x12*\n" +
	"\x11target_block_time\x18\x01 \x01(\rR\x0ftargetBlockTime\x12D\n" +
	"\x1edifficulty_adjustment_interval\x18\x02 \x01(\rR\x1cdifficultyAdjustmentInterval\x120\n" +
	"\x14reward_lockup_period\x18\x03 \x01(\rR\x12rewardLockupPeriod\x12=\n" +
	"\x1bmempool_nano_reset_interval\x18\x04 \x01(\rR\x18mempoolNanoResetInterval\x12$\n" +
	"\x0emax_block_size\x18\x05 \x01(\rR\fmaxBlockSizeJ\x04\b\x06\x10\a\"\x98\x01\n" +
	"\n" +
	"MiningTask\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.btc_genz.block.BlockHeaderR\x06header\x12\x18\n" +
	"\athreads\x18\x02 \x01(\rR\athreads\x12\x1c\n" +
	"\tintensity\x18\x03 \x01(\rR\tintensity\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\x04R\tsessionId\"|\n" +
	"\fMiningResult\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\x04R\tsessionId\"\x96\x01\n" +
	"\x15BlockExecutionRequest\x12$\n" +
	"\x0eblock_body_raw\x18\x01 \x01(\fR\fblockBodyRaw\x12#\n" +
	"\rminer_address\x18\x02 \x01(\fR\fminerAddress\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x04R\x06height\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\x04R\x05nonceJ\x04\b\x05\x10\x06\"1\n" +
	"\x10SyncChainRequest\x12\x1d\n" +
	"\n" +
	"blocks_raw\x18\x01 \x03(\fR\tblocksRaw\"\xe4\x01\n" +
	"\x0fSyncInstruction\x12H\n" +
	"\bstrategy\x18\x01 \x01(\x0e2,.btc_genz.consensus.SyncInstruction.StrategyR\bstrategy\x12!\n" +
	"\fstart_height\x18\x02 \x01(\x04R\vstartHeight\x12\x1d\n" +
	"\n" +
	"end_height\x18\x03 \x01(\x04R\tendHeight\"E\n" +
	"\bStrategy\x12\f\n" +
	"\bCONTINUE\x10\x00\x12\r\n" +
	"\tBACKTRACK\x10\x01\x12\t\n" +
	"\x05STALL\x10\x02\x12\x11\n" +
	"\rDEEP_RECOVERY\x10\x03\"\xe1\x03\n" +
	"\x11SyncChainResponse\x12D\n" +
	"\x06status\x18\x01 \x01(\x0e2,.btc_genz.consensus.SyncChainResponse.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"new_height\x18\x02 \x01(\x04R\tnewHeight\x12\x1d\n" +
	"\n" +
	"fork_point\x18\x03 \x01(\x04R\tforkPoint\x12,\n" +
	"\x12orphaned_tx_hashes\x18\x04 \x03(\fR\x10orphanedTxHashes\x12(\n" +
	"\x10orphaned_txs_raw\x18\x06 \x03(\fR\x0eorphanedTxsRaw\x12\x1b\n" +
	"\terror_msg\x18\x05 \x01(\tR\berrorMsg\x12.\n" +
	"\x13missing_parent_hash\x18\a \x01(\tR\x11missingParentHash\x12E\n" +
	"\vinstruction\x18\b \x01(\v2#.btc_genz.consensus.SyncInstructionR\vinstruction\"\\\n" +
	"\x06Status\x12\f\n" +
	"\bACCEPTED\x10\x00\x12\x11\n" +
	"\rREORG_SUCCESS\x10\x01\x12\x11\n" +
	"\rINVALID_CHAIN\x10\x02\x12\n" +
	"\n" +
	"\x06ORPHAN\x10\x03\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x04B\x10Z\x0ebtc_genz/protob\x06proto3"

var (
	file_consensus_consensus_proto_rawDescOnce sync.Once
	file_consensus_consensus_proto_rawDescData []byte
)

func file_consensus_consensus_proto_rawDescGZIP() []byte {
	file_consensus_consensus_proto_rawDescOnce.Do(func() {
		file_consensus_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consensus_consensus_proto_rawDesc), len(file_consensus_consensus_proto_rawDesc)))
	})
	return file_consensus_consensus_proto_rawDescData
}

var file_consensus_consensus_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_consensus_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_consensus_consensus_proto_goTypes = []any{
	(SyncInstruction_Strategy)(0), // 0: btc_genz.consensus.SyncInstruction.Strategy
	(SyncChainResponse_Status)(0), // 1: btc_genz.consensus.SyncChainResponse.Status
	(*ConsensusParams)(nil),       // 2: btc_genz.consensus.ConsensusParams
	(*MiningTask)(nil),            // 3: btc_genz.consensus.MiningTask
	(*MiningResult)(nil),          // 4: btc_genz.consensus.MiningResult
	(*BlockExecutionRequest)(nil), // 5: btc_genz.consensus.BlockExecutionRequest
	(*SyncChainRequest)(nil),      // 6: btc_genz.consensus.SyncChainRequest
	(*SyncInstruction)(nil),       // 7: btc_genz.consensus.SyncInstruction
	(*SyncChainResponse)(nil),     // 8: btc_genz.consensus.SyncChainResponse
	(*BlockHeader)(nil),           // 9: btc_genz.block.BlockHeader
}
var file_consensus_consensus_proto_depIdxs = []int32{
	9, // 0: btc_genz.consensus.MiningTask.header:type_name -> btc_genz.block.BlockHeader
	0, // 1: btc_genz.consensus.SyncInstruction.strategy:type_name -> btc_genz.consensus.SyncInstruction.Strategy
	1, // 2: btc_genz.consensus.SyncChainResponse.status:type_name -> btc_genz.consensus.SyncChainResponse.Status
	7, // 3: btc_genz.consensus.SyncChainResponse.instruction:type_name -> btc_genz.consensus.SyncInstruction
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_consensus_consensus_proto_init() }
func file_consensus_consensus_proto_init() {
	if File_consensus_consensus_proto != nil {
		return
	}
	file_block_block_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consensus_consensus_proto_rawDesc), len(file_consensus_consensus_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consensus_consensus_proto_goTypes,
		DependencyIndexes: file_consensus_consensus_proto_depIdxs,
		EnumInfos:         file_consensus_consensus_proto_enumTypes,
		MessageInfos:      file_consensus_consensus_proto_msgTypes,
	}.Build()
	File_consensus_consensus_proto = out.File
	file_consensus_consensus_proto_goTypes = nil
	file_consensus_consensus_proto_depIdxs = nil
}
