//*
// @file miner.proto
// @brief Định nghĩa giao diện gRPC gữa Go Node (Chỉ huy) và genz_miner.exe (Thợ đào).
// @date 2026-06-23

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: consensus/miner.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MinerGateway_ConnectMiner_FullMethodName = "/btc_genz.consensus.MinerGateway/ConnectMiner"
)

// MinerGatewayClient is the client API for MinerGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MinerGatewayClient interface {
	// Luồng gRPC 2 chiều: Miner gửi thông tin lên, Node gửi lệnh xuống
	ConnectMiner(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MinerMessage, NodeCommand], error)
}

type minerGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewMinerGatewayClient(cc grpc.ClientConnInterface) MinerGatewayClient {
	return &minerGatewayClient{cc}
}

func (c *minerGatewayClient) ConnectMiner(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MinerMessage, NodeCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MinerGateway_ServiceDesc.Streams[0], MinerGateway_ConnectMiner_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MinerMessage, NodeCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinerGateway_ConnectMinerClient = grpc.BidiStreamingClient[MinerMessage, NodeCommand]

// MinerGatewayServer is the server API for MinerGateway service.
// All implementations should embed UnimplementedMinerGatewayServer
// for forward compatibility.
type MinerGatewayServer interface {
	// Luồng gRPC 2 chiều: Miner gửi thông tin lên, Node gửi lệnh xuống
	ConnectMiner(grpc.BidiStreamingServer[MinerMessage, NodeCommand]) error
}

// UnimplementedMinerGatewayServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMinerGatewayServer struct{}

func (UnimplementedMinerGatewayServer) ConnectMiner(grpc.BidiStreamingServer[MinerMessage, NodeCommand]) error {
	return status.Error(codes.Unimplemented, "method ConnectMiner not implemented")
}
func (UnimplementedMinerGatewayServer) testEmbeddedByValue() {}

// UnsafeMinerGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MinerGatewayServer will
// result in compilation errors.
type UnsafeMinerGatewayServer interface {
	mustEmbedUnimplementedMinerGatewayServer()
}

func RegisterMinerGatewayServer(s grpc.ServiceRegistrar, srv MinerGatewayServer) {
	// If the following call panics, it indicates UnimplementedMinerGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MinerGateway_ServiceDesc, srv)
}

func _MinerGateway_ConnectMiner_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MinerGatewayServer).ConnectMiner(&grpc.GenericServerStream[MinerMessage, NodeCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinerGateway_ConnectMinerServer = grpc.BidiStreamingServer[MinerMessage, NodeCommand]

// MinerGateway_ServiceDesc is the grpc.ServiceDesc for MinerGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MinerGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "btc_genz.consensus.MinerGateway",
	HandlerType: (*MinerGatewayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConnectMiner",
			Handler:       _MinerGateway_ConnectMiner_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "consensus/miner.proto",
}
