//*
// @file miner.proto
// @brief Định nghĩa giao diện gRPC gữa Go Node (Chỉ huy) và genz_miner.exe (Thợ đào).
// @date 2026-06-23

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: consensus/miner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeCommand struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IsPaused         bool                   `protobuf:"varint,1,opt,name=is_paused,json=isPaused,proto3" json:"is_paused,omitempty"`                         // Trạng thái Tắt/Bật đào từ giao diện điều khiển
	CpuIntensity     uint32                 `protobuf:"varint,2,opt,name=cpu_intensity,json=cpuIntensity,proto3" json:"cpu_intensity,omitempty"`             // Cường độ CPU tối đa (1-100%)
	BlockTemplate    []byte                 `protobuf:"bytes,3,opt,name=block_template,json=blockTemplate,proto3" json:"block_template,omitempty"`           // Dữ liệu block header thô cần băm (MiningTask serialized bytes)
	TargetDifficulty uint64                 `protobuf:"varint,4,opt,name=target_difficulty,json=targetDifficulty,proto3" json:"target_difficulty,omitempty"` // Độ khó mục tiêu (Target difficulty)
	SessionId        uint64                 `protobuf:"varint,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                      // ID phiên khai thác hiện tại để phân biệt các block cũ/mới
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeCommand) Reset() {
	*x = NodeCommand{}
	mi := &file_consensus_miner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCommand) ProtoMessage() {}

func (x *NodeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_miner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCommand.ProtoReflect.Descriptor instead.
func (*NodeCommand) Descriptor() ([]byte, []int) {
	return file_consensus_miner_proto_rawDescGZIP(), []int{0}
}

func (x *NodeCommand) GetIsPaused() bool {
	if x != nil {
		return x.IsPaused
	}
	return false
}

func (x *NodeCommand) GetCpuIntensity() uint32 {
	if x != nil {
		return x.CpuIntensity
	}
	return 0
}

func (x *NodeCommand) GetBlockTemplate() []byte {
	if x != nil {
		return x.BlockTemplate
	}
	return nil
}

func (x *NodeCommand) GetTargetDifficulty() uint64 {
	if x != nil {
		return x.TargetDifficulty
	}
	return 0
}

func (x *NodeCommand) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type MinerMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentHashrate uint64                 `protobuf:"varint,1,opt,name=current_hashrate,json=currentHashrate,proto3" json:"current_hashrate,omitempty"` // Hashrate thực tế (H/s) báo cáo lên UI
	FoundNonce      uint64                 `protobuf:"varint,2,opt,name=found_nonce,json=foundNonce,proto3" json:"found_nonce,omitempty"`                // Nonce kết quả đào được để đóng block
	BlockHash       []byte                 `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`                    // Hash của block đào được
	SessionId       uint64                 `protobuf:"varint,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                   // ID phiên tương ứng của kết quả
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MinerMessage) Reset() {
	*x = MinerMessage{}
	mi := &file_consensus_miner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinerMessage) ProtoMessage() {}

func (x *MinerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_miner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinerMessage.ProtoReflect.Descriptor instead.
func (*MinerMessage) Descriptor() ([]byte, []int) {
	return file_consensus_miner_proto_rawDescGZIP(), []int{1}
}

func (x *MinerMessage) GetCurrentHashrate() uint64 {
	if x != nil {
		return x.CurrentHashrate
	}
	return 0
}

func (x *MinerMessage) GetFoundNonce() uint64 {
	if x != nil {
		return x.FoundNonce
	}
	return 0
}

func (x *MinerMessage) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *MinerMessage) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

var File_consensus_miner_proto protoreflect.FileDescriptor

const file_consensus_miner_proto_rawDesc = "" +
	"\n" +
	"\x15consensus/miner.proto\x12\x12btc_genz.consensus\"\xc2\x01\n" +
	"\vNodeCommand\x12\x1b\n" +
	"\tis_paused\x18\x01 \x01(\bR\bisPaused\x12#\n" +
	"\rcpu_intensity\x18\x02 \x01(\rR\fcpuIntensity\x12%\n" +
	"\x0eblock_template\x18\x03 \x01(\fR\rblockTemplate\x12+\n" +
	"\x11target_difficulty\x18\x04 \x01(\x04R\x10targetDifficulty\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\x04R\tsessionId\"\x98\x01\n" +
	"\fMinerMessage\x12)\n" +
	"\x10current_hashrate\x18\x01 \x01(\x04R\x0fcurrentHashrate\x12\x1f\n" +
	"\vfound_nonce\x18\x02 \x01(\x04R\n" +
	"foundNonce\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x03 \x01(\fR\tblockHash\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\x04R\tsessionId2e\n" +
	"\fMinerGateway\x12U\n" +
	"\fConnectMiner\x12 .btc_genz.consensus.MinerMessage\x1a\x1f.btc_genz.consensus.NodeCommand(\x010\x01B\x10Z\x0ebtc_genz/protob\x06proto3"

var (
	file_consensus_miner_proto_rawDescOnce sync.Once
	file_consensus_miner_proto_rawDescData []byte
)

func file_consensus_miner_proto_rawDescGZIP() []byte {
	file_consensus_miner_proto_rawDescOnce.Do(func() {
		file_consensus_miner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consensus_miner_proto_rawDesc), len(file_consensus_miner_proto_rawDesc)))
	})
	return file_consensus_miner_proto_rawDescData
}

var file_consensus_miner_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_consensus_miner_proto_goTypes = []any{
	(*NodeCommand)(nil),  // 0: btc_genz.consensus.NodeCommand
	(*MinerMessage)(nil), // 1: btc_genz.consensus.MinerMessage
}
var file_consensus_miner_proto_depIdxs = []int32{
	1, // 0: btc_genz.consensus.MinerGateway.ConnectMiner:input_type -> btc_genz.consensus.MinerMessage
	0, // 1: btc_genz.consensus.MinerGateway.ConnectMiner:output_type -> btc_genz.consensus.NodeCommand
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_consensus_miner_proto_init() }
func file_consensus_miner_proto_init() {
	if File_consensus_miner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consensus_miner_proto_rawDesc), len(file_consensus_miner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_consensus_miner_proto_goTypes,
		DependencyIndexes: file_consensus_miner_proto_depIdxs,
		MessageInfos:      file_consensus_miner_proto_msgTypes,
	}.Build()
	File_consensus_miner_proto = out.File
	file_consensus_miner_proto_goTypes = nil
	file_consensus_miner_proto_depIdxs = nil
}
