//*
// @file network.proto
// @brief Định nghĩa các giao thức truyền tải mạng P2P và RPC.
// @details Chứa các bản tin dùng cho Gossipsub (phát sóng khối/tx)
// và các yêu cầu RPC (GetBlock, Handshake).
// Đảm bảo sự đồng bộ hóa tức thời giữa các Node trong mạng lưới.
//
// @author Vô Nhật Thiên (Khởi tạo)
// @date 2026-03-18

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: network/network.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlockchainService_GetBlock_FullMethodName                 = "/btc_genz.network.BlockchainService/GetBlock"
	BlockchainService_GetHeaderBatch_FullMethodName           = "/btc_genz.network.BlockchainService/GetHeaderBatch"
	BlockchainService_SubmitTransaction_FullMethodName        = "/btc_genz.network.BlockchainService/SubmitTransaction"
	BlockchainService_GetStatus_FullMethodName                = "/btc_genz.network.BlockchainService/GetStatus"
	BlockchainService_GetAccount_FullMethodName               = "/btc_genz.network.BlockchainService/GetAccount"
	BlockchainService_CalculateBlockHeaderHash_FullMethodName = "/btc_genz.network.BlockchainService/CalculateBlockHeaderHash"
	BlockchainService_StartMining_FullMethodName              = "/btc_genz.network.BlockchainService/StartMining"
	BlockchainService_StopMining_FullMethodName               = "/btc_genz.network.BlockchainService/StopMining"
)

// BlockchainServiceClient is the client API for BlockchainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// [V4.30] CÔNG NGHIỆP HÓA: Blockchain gRPC Service
type BlockchainServiceClient interface {
	// Truy vấn dữ liệu khối
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error)
	// [V5.0] Truy vấn hàng loạt Header (Batch Sync)
	GetHeaderBatch(ctx context.Context, in *GetHeaderBatchRequest, opts ...grpc.CallOption) (*GetHeaderBatchResponse, error)
	// Gửi giao dịch mới vào Mempool
	SubmitTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Hash, error)
	// [V11.0.3] Truy vấn trạng thái vận hành của Node (S#5 FIX)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// [Audit S3 FIX] Truy vấn số dư và Nonce thực tế của tài khoản
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*AccountResponse, error)
	// Tính toán mã Hash của Header khối (Dùng cho ký giao dịch)
	CalculateBlockHeaderHash(ctx context.Context, in *RawBytes, opts ...grpc.CallOption) (*Hash, error)
	// [MINING] Điều khiển khai thác từ xa
	StartMining(ctx context.Context, in *StartMiningRequest, opts ...grpc.CallOption) (*MiningResponse, error)
	StopMining(ctx context.Context, in *StopMiningRequest, opts ...grpc.CallOption) (*MiningResponse, error)
}

type blockchainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockchainServiceClient(cc grpc.ClientConnInterface) BlockchainServiceClient {
	return &blockchainServiceClient{cc}
}

func (c *blockchainServiceClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockResponse)
	err := c.cc.Invoke(ctx, BlockchainService_GetBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) GetHeaderBatch(ctx context.Context, in *GetHeaderBatchRequest, opts ...grpc.CallOption) (*GetHeaderBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHeaderBatchResponse)
	err := c.cc.Invoke(ctx, BlockchainService_GetHeaderBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) SubmitTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Hash, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Hash)
	err := c.cc.Invoke(ctx, BlockchainService_SubmitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, BlockchainService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountResponse)
	err := c.cc.Invoke(ctx, BlockchainService_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) CalculateBlockHeaderHash(ctx context.Context, in *RawBytes, opts ...grpc.CallOption) (*Hash, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Hash)
	err := c.cc.Invoke(ctx, BlockchainService_CalculateBlockHeaderHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) StartMining(ctx context.Context, in *StartMiningRequest, opts ...grpc.CallOption) (*MiningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MiningResponse)
	err := c.cc.Invoke(ctx, BlockchainService_StartMining_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) StopMining(ctx context.Context, in *StopMiningRequest, opts ...grpc.CallOption) (*MiningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MiningResponse)
	err := c.cc.Invoke(ctx, BlockchainService_StopMining_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockchainServiceServer is the server API for BlockchainService service.
// All implementations should embed UnimplementedBlockchainServiceServer
// for forward compatibility.
//
// [V4.30] CÔNG NGHIỆP HÓA: Blockchain gRPC Service
type BlockchainServiceServer interface {
	// Truy vấn dữ liệu khối
	GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error)
	// [V5.0] Truy vấn hàng loạt Header (Batch Sync)
	GetHeaderBatch(context.Context, *GetHeaderBatchRequest) (*GetHeaderBatchResponse, error)
	// Gửi giao dịch mới vào Mempool
	SubmitTransaction(context.Context, *Transaction) (*Hash, error)
	// [V11.0.3] Truy vấn trạng thái vận hành của Node (S#5 FIX)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// [Audit S3 FIX] Truy vấn số dư và Nonce thực tế của tài khoản
	GetAccount(context.Context, *GetAccountRequest) (*AccountResponse, error)
	// Tính toán mã Hash của Header khối (Dùng cho ký giao dịch)
	CalculateBlockHeaderHash(context.Context, *RawBytes) (*Hash, error)
	// [MINING] Điều khiển khai thác từ xa
	StartMining(context.Context, *StartMiningRequest) (*MiningResponse, error)
	StopMining(context.Context, *StopMiningRequest) (*MiningResponse, error)
}

// UnimplementedBlockchainServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockchainServiceServer struct{}

func (UnimplementedBlockchainServiceServer) GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlock not implemented")
}
func (UnimplementedBlockchainServiceServer) GetHeaderBatch(context.Context, *GetHeaderBatchRequest) (*GetHeaderBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHeaderBatch not implemented")
}
func (UnimplementedBlockchainServiceServer) SubmitTransaction(context.Context, *Transaction) (*Hash, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (UnimplementedBlockchainServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedBlockchainServiceServer) GetAccount(context.Context, *GetAccountRequest) (*AccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedBlockchainServiceServer) CalculateBlockHeaderHash(context.Context, *RawBytes) (*Hash, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateBlockHeaderHash not implemented")
}
func (UnimplementedBlockchainServiceServer) StartMining(context.Context, *StartMiningRequest) (*MiningResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartMining not implemented")
}
func (UnimplementedBlockchainServiceServer) StopMining(context.Context, *StopMiningRequest) (*MiningResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopMining not implemented")
}
func (UnimplementedBlockchainServiceServer) testEmbeddedByValue() {}

// UnsafeBlockchainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockchainServiceServer will
// result in compilation errors.
type UnsafeBlockchainServiceServer interface {
	mustEmbedUnimplementedBlockchainServiceServer()
}

func RegisterBlockchainServiceServer(s grpc.ServiceRegistrar, srv BlockchainServiceServer) {
	// If the following call panics, it indicates UnimplementedBlockchainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockchainService_ServiceDesc, srv)
}

func _BlockchainService_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainService_GetBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_GetHeaderBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHeaderBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).GetHeaderBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainService_GetHeaderBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).GetHeaderBatch(ctx, req.(*GetHeaderBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainService_SubmitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).SubmitTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainService_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_CalculateBlockHeaderHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawBytes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).CalculateBlockHeaderHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainService_CalculateBlockHeaderHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).CalculateBlockHeaderHash(ctx, req.(*RawBytes))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_StartMining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartMiningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).StartMining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainService_StartMining_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).StartMining(ctx, req.(*StartMiningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_StopMining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopMiningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).StopMining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainService_StopMining_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).StopMining(ctx, req.(*StopMiningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockchainService_ServiceDesc is the grpc.ServiceDesc for BlockchainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockchainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "btc_genz.network.BlockchainService",
	HandlerType: (*BlockchainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlock",
			Handler:    _BlockchainService_GetBlock_Handler,
		},
		{
			MethodName: "GetHeaderBatch",
			Handler:    _BlockchainService_GetHeaderBatch_Handler,
		},
		{
			MethodName: "SubmitTransaction",
			Handler:    _BlockchainService_SubmitTransaction_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _BlockchainService_GetStatus_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _BlockchainService_GetAccount_Handler,
		},
		{
			MethodName: "CalculateBlockHeaderHash",
			Handler:    _BlockchainService_CalculateBlockHeaderHash_Handler,
		},
		{
			MethodName: "StartMining",
			Handler:    _BlockchainService_StartMining_Handler,
		},
		{
			MethodName: "StopMining",
			Handler:    _BlockchainService_StopMining_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "network/network.proto",
}
