//*
// @file network.proto
// @brief Định nghĩa các giao thức truyền tải mạng P2P và RPC.
// @details Chứa các bản tin dùng cho Gossipsub (phát sóng khối/tx)
// và các yêu cầu RPC (GetBlock, Handshake).
// Đảm bảo sự đồng bộ hóa tức thời giữa các Node trong mạng lưới.
//
// @author Vô Nhật Thiên (Khởi tạo)
// @date 2026-03-18

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: network/network.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WarningMsg_WarningType int32

const (
	WarningMsg_FIREWALL_VIOLATION WarningMsg_WarningType = 0
	WarningMsg_INVALID_POW        WarningMsg_WarningType = 1
	WarningMsg_TIME_WARP_ATTEMPT  WarningMsg_WarningType = 2
)

// Enum value maps for WarningMsg_WarningType.
var (
	WarningMsg_WarningType_name = map[int32]string{
		0: "FIREWALL_VIOLATION",
		1: "INVALID_POW",
		2: "TIME_WARP_ATTEMPT",
	}
	WarningMsg_WarningType_value = map[string]int32{
		"FIREWALL_VIOLATION": 0,
		"INVALID_POW":        1,
		"TIME_WARP_ATTEMPT":  2,
	}
)

func (x WarningMsg_WarningType) Enum() *WarningMsg_WarningType {
	p := new(WarningMsg_WarningType)
	*p = x
	return p
}

func (x WarningMsg_WarningType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WarningMsg_WarningType) Descriptor() protoreflect.EnumDescriptor {
	return file_network_network_proto_enumTypes[0].Descriptor()
}

func (WarningMsg_WarningType) Type() protoreflect.EnumType {
	return &file_network_network_proto_enumTypes[0]
}

func (x WarningMsg_WarningType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WarningMsg_WarningType.Descriptor instead.
func (WarningMsg_WarningType) EnumDescriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{17, 0}
}

// Dòng dữ liệu thô
type RawBytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawBytes) Reset() {
	*x = RawBytes{}
	mi := &file_network_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawBytes) ProtoMessage() {}

func (x *RawBytes) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawBytes.ProtoReflect.Descriptor instead.
func (*RawBytes) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{0}
}

func (x *RawBytes) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Yêu cầu lấy trạng thái tài khoản
type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_network_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountRequest) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

// Phản hồi trạng thái tài khoản (S3 Fix)
type AccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       uint64                 `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Nonce         uint64                 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Address       []byte                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	mi := &file_network_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{2}
}

func (x *AccountResponse) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *AccountResponse) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *AccountResponse) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

// Tin nhắn phát sóng Khối mới (Gossipsub)
type NewBlockMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewBlockMsg) Reset() {
	*x = NewBlockMsg{}
	mi := &file_network_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewBlockMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewBlockMsg) ProtoMessage() {}

func (x *NewBlockMsg) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewBlockMsg.ProtoReflect.Descriptor instead.
func (*NewBlockMsg) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{3}
}

func (x *NewBlockMsg) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

// Tin nhắn phát sóng Giao dịch mới
type NewTxMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            *Transaction           `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewTxMsg) Reset() {
	*x = NewTxMsg{}
	mi := &file_network_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewTxMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTxMsg) ProtoMessage() {}

func (x *NewTxMsg) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTxMsg.ProtoReflect.Descriptor instead.
func (*NewTxMsg) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{4}
}

func (x *NewTxMsg) GetTx() *Transaction {
	if x != nil {
		return x.Tx
	}
	return nil
}

// [V1.0 MINIMALIST] Tin nhắn phát sóng thông báo Khối mới (Inventory)
type InventoryMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryMsg) Reset() {
	*x = InventoryMsg{}
	mi := &file_network_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryMsg) ProtoMessage() {}

func (x *InventoryMsg) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryMsg.ProtoReflect.Descriptor instead.
func (*InventoryMsg) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{5}
}

func (x *InventoryMsg) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *InventoryMsg) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// Yêu cầu lấy dữ liệu khối theo chiều cao
type GetBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"` // [VANGUARD-ORPHAN] Yêu cầu theo mã băm để giải quyết mồ côi
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockRequest) Reset() {
	*x = GetBlockRequest{}
	mi := &file_network_network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRequest) ProtoMessage() {}

func (x *GetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{6}
}

func (x *GetBlockRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GetBlockRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// Phản hồi dữ liệu khối
type GetBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockResponse) Reset() {
	*x = GetBlockResponse{}
	mi := &file_network_network_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockResponse) ProtoMessage() {}

func (x *GetBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockResponse.ProtoReflect.Descriptor instead.
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{7}
}

func (x *GetBlockResponse) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *GetBlockResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// Tin nhắn bắt tay (Handshake)
type Handshake struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	GenesisHash     []byte                 `protobuf:"bytes,2,opt,name=genesis_hash,json=genesisHash,proto3" json:"genesis_hash,omitempty"`
	CurrentHeight   uint64                 `protobuf:"varint,3,opt,name=current_height,json=currentHeight,proto3" json:"current_height,omitempty"`
	Timestamp       uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FinalizedHeight uint64                 `protobuf:"varint,5,opt,name=finalized_height,json=finalizedHeight,proto3" json:"finalized_height,omitempty"` // [V38.2] Điểm chốt Snapshot gần nhất (Checkpoint)
	OldestHeight    uint64                 `protobuf:"varint,6,opt,name=oldest_height,json=oldestHeight,proto3" json:"oldest_height,omitempty"`          // [V38.3] Khối cũ nhất còn tồn tại trên đĩa (Sau Purge)
	NatStatus       uint32                 `protobuf:"varint,7,opt,name=nat_status,json=natStatus,proto3" json:"nat_status,omitempty"`                   // [NAT-AUDIT] Trạng thái NAT: 0=Chưa xác định, 1=Public (mở tường lửa), 2=Private (đằng sau NAT)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_network_network_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{8}
}

func (x *Handshake) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Handshake) GetGenesisHash() []byte {
	if x != nil {
		return x.GenesisHash
	}
	return nil
}

func (x *Handshake) GetCurrentHeight() uint64 {
	if x != nil {
		return x.CurrentHeight
	}
	return 0
}

func (x *Handshake) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Handshake) GetFinalizedHeight() uint64 {
	if x != nil {
		return x.FinalizedHeight
	}
	return 0
}

func (x *Handshake) GetOldestHeight() uint64 {
	if x != nil {
		return x.OldestHeight
	}
	return 0
}

func (x *Handshake) GetNatStatus() uint32 {
	if x != nil {
		return x.NatStatus
	}
	return 0
}

// [V4.11] Tin nhắn Chứng chỉ Vệ binh (Voluntary Sentinel Certificate)
type SentinelCertificateMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        []byte                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // 32 bytes
	StartBlock    uint64                 `protobuf:"varint,2,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	Challenge     []byte                 `protobuf:"bytes,3,opt,name=challenge,proto3" json:"challenge,omitempty"`
	TIterations   uint64                 `protobuf:"varint,4,opt,name=t_iterations,json=tIterations,proto3" json:"t_iterations,omitempty"`
	Solution      []byte                 `protobuf:"bytes,5,opt,name=solution,proto3" json:"solution,omitempty"`
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"` // 64 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentinelCertificateMsg) Reset() {
	*x = SentinelCertificateMsg{}
	mi := &file_network_network_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentinelCertificateMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentinelCertificateMsg) ProtoMessage() {}

func (x *SentinelCertificateMsg) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentinelCertificateMsg.ProtoReflect.Descriptor instead.
func (*SentinelCertificateMsg) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{9}
}

func (x *SentinelCertificateMsg) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *SentinelCertificateMsg) GetStartBlock() uint64 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *SentinelCertificateMsg) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *SentinelCertificateMsg) GetTIterations() uint64 {
	if x != nil {
		return x.TIterations
	}
	return 0
}

func (x *SentinelCertificateMsg) GetSolution() []byte {
	if x != nil {
		return x.Solution
	}
	return nil
}

func (x *SentinelCertificateMsg) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// [V5.0] Yêu cầu lấy hàng loạt Header (Batch Sync)
type GetHeaderBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartHeight   uint64                 `protobuf:"varint,1,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeaderBatchRequest) Reset() {
	*x = GetHeaderBatchRequest{}
	mi := &file_network_network_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeaderBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeaderBatchRequest) ProtoMessage() {}

func (x *GetHeaderBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeaderBatchRequest.ProtoReflect.Descriptor instead.
func (*GetHeaderBatchRequest) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{10}
}

func (x *GetHeaderBatchRequest) GetStartHeight() uint64 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

func (x *GetHeaderBatchRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetHeaderBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       [][]byte               `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"` // Danh sách các Header đã nén (Serialized)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeaderBatchResponse) Reset() {
	*x = GetHeaderBatchResponse{}
	mi := &file_network_network_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeaderBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeaderBatchResponse) ProtoMessage() {}

func (x *GetHeaderBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeaderBatchResponse.ProtoReflect.Descriptor instead.
func (*GetHeaderBatchResponse) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{11}
}

func (x *GetHeaderBatchResponse) GetHeaders() [][]byte {
	if x != nil {
		return x.Headers
	}
	return nil
}

// [V11.0.3] Yêu cầu trạng thái Node (S#5 FIX)
type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_network_network_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{12}
}

// [V11.0.3] Phản hồi trạng thái Node (S#5 FIX)
type GetStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentHeight   uint64                 `protobuf:"varint,1,opt,name=current_height,json=currentHeight,proto3" json:"current_height,omitempty"`
	FinalizedHeight uint64                 `protobuf:"varint,2,opt,name=finalized_height,json=finalizedHeight,proto3" json:"finalized_height,omitempty"`
	Hashrate        uint64                 `protobuf:"varint,3,opt,name=hashrate,proto3" json:"hashrate,omitempty"`
	IsMining        bool                   `protobuf:"varint,4,opt,name=is_mining,json=isMining,proto3" json:"is_mining,omitempty"`
	Version         string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	PeerCount       uint32                 `protobuf:"varint,6,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	Difficulty      uint32                 `protobuf:"varint,7,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	OldestHeight    uint64                 `protobuf:"varint,8,opt,name=oldest_height,json=oldestHeight,proto3" json:"oldest_height,omitempty"` // [V38.3] Ranh giới dữ liệu thực tế
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_network_network_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{13}
}

func (x *GetStatusResponse) GetCurrentHeight() uint64 {
	if x != nil {
		return x.CurrentHeight
	}
	return 0
}

func (x *GetStatusResponse) GetFinalizedHeight() uint64 {
	if x != nil {
		return x.FinalizedHeight
	}
	return 0
}

func (x *GetStatusResponse) GetHashrate() uint64 {
	if x != nil {
		return x.Hashrate
	}
	return 0
}

func (x *GetStatusResponse) GetIsMining() bool {
	if x != nil {
		return x.IsMining
	}
	return false
}

func (x *GetStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetStatusResponse) GetPeerCount() uint32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

func (x *GetStatusResponse) GetDifficulty() uint32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *GetStatusResponse) GetOldestHeight() uint64 {
	if x != nil {
		return x.OldestHeight
	}
	return 0
}

// [MINING] Yêu cầu bắt đầu đào
type StartMiningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinerAddress  string                 `protobuf:"bytes,1,opt,name=miner_address,json=minerAddress,proto3" json:"miner_address,omitempty"`
	Threads       uint32                 `protobuf:"varint,2,opt,name=threads,proto3" json:"threads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMiningRequest) Reset() {
	*x = StartMiningRequest{}
	mi := &file_network_network_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMiningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMiningRequest) ProtoMessage() {}

func (x *StartMiningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMiningRequest.ProtoReflect.Descriptor instead.
func (*StartMiningRequest) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{14}
}

func (x *StartMiningRequest) GetMinerAddress() string {
	if x != nil {
		return x.MinerAddress
	}
	return ""
}

func (x *StartMiningRequest) GetThreads() uint32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

// [MINING] Yêu cầu dừng đào
type StopMiningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopMiningRequest) Reset() {
	*x = StopMiningRequest{}
	mi := &file_network_network_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopMiningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMiningRequest) ProtoMessage() {}

func (x *StopMiningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMiningRequest.ProtoReflect.Descriptor instead.
func (*StopMiningRequest) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{15}
}

// [MINING] Phản hồi kết quả điều khiển
type MiningResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiningResponse) Reset() {
	*x = MiningResponse{}
	mi := &file_network_network_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiningResponse) ProtoMessage() {}

func (x *MiningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiningResponse.ProtoReflect.Descriptor instead.
func (*MiningResponse) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{16}
}

func (x *MiningResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MiningResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// [V1.5.0] Tin nhắn cảnh báo P2P khi vi phạm Tường lửa (Firewall Violation Feedback)
type WarningMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WarningMsg_WarningType `protobuf:"varint,1,opt,name=type,proto3,enum=btc_genz.network.WarningMsg_WarningType" json:"type,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	RejectHash    []byte                 `protobuf:"bytes,3,opt,name=reject_hash,json=rejectHash,proto3" json:"reject_hash,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarningMsg) Reset() {
	*x = WarningMsg{}
	mi := &file_network_network_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarningMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarningMsg) ProtoMessage() {}

func (x *WarningMsg) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarningMsg.ProtoReflect.Descriptor instead.
func (*WarningMsg) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{17}
}

func (x *WarningMsg) GetType() WarningMsg_WarningType {
	if x != nil {
		return x.Type
	}
	return WarningMsg_FIREWALL_VIOLATION
}

func (x *WarningMsg) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *WarningMsg) GetRejectHash() []byte {
	if x != nil {
		return x.RejectHash
	}
	return nil
}

func (x *WarningMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_network_network_proto protoreflect.FileDescriptor

const file_network_network_proto_rawDesc = "" +
	"\n" +
	"\x15network/network.proto\x12\x10btc_genz.network\x1a\x11block/block.proto\x1a\x1dtransaction/transaction.proto\x1a\x13common/common.proto\"\x1e\n" +
	"\bRawBytes\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"-\n" +
	"\x11GetAccountRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\"[\n" +
	"\x0fAccountResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x04R\abalance\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\fR\aaddress\":\n" +
	"\vNewBlockMsg\x12+\n" +
	"\x05block\x18\x01 \x01(\v2\x15.btc_genz.block.BlockR\x05block\"=\n" +
	"\bNewTxMsg\x121\n" +
	"\x02tx\x18\x01 \x01(\v2!.btc_genz.transaction.TransactionR\x02tx\":\n" +
	"\fInventoryMsg\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"=\n" +
	"\x0fGetBlockRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"U\n" +
	"\x10GetBlockResponse\x12+\n" +
	"\x05block\x18\x01 \x01(\v2\x15.btc_genz.block.BlockR\x05block\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\xfc\x01\n" +
	"\tHandshake\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12!\n" +
	"\fgenesis_hash\x18\x02 \x01(\fR\vgenesisHash\x12%\n" +
	"\x0ecurrent_height\x18\x03 \x01(\x04R\rcurrentHeight\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12)\n" +
	"\x10finalized_height\x18\x05 \x01(\x04R\x0ffinalizedHeight\x12#\n" +
	"\roldest_height\x18\x06 \x01(\x04R\foldestHeight\x12\x1d\n" +
	"\n" +
	"nat_status\x18\a \x01(\rR\tnatStatus\"\xcd\x01\n" +
	"\x16SentinelCertificateMsg\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x1f\n" +
	"\vstart_block\x18\x02 \x01(\x04R\n" +
	"startBlock\x12\x1c\n" +
	"\tchallenge\x18\x03 \x01(\fR\tchallenge\x12!\n" +
	"\ft_iterations\x18\x04 \x01(\x04R\vtIterations\x12\x1a\n" +
	"\bsolution\x18\x05 \x01(\fR\bsolution\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\"P\n" +
	"\x15GetHeaderBatchRequest\x12!\n" +
	"\fstart_height\x18\x01 \x01(\x04R\vstartHeight\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"2\n" +
	"\x16GetHeaderBatchResponse\x12\x18\n" +
	"\aheaders\x18\x01 \x03(\fR\aheaders\"\x12\n" +
	"\x10GetStatusRequest\"\x9c\x02\n" +
	"\x11GetStatusResponse\x12%\n" +
	"\x0ecurrent_height\x18\x01 \x01(\x04R\rcurrentHeight\x12)\n" +
	"\x10finalized_height\x18\x02 \x01(\x04R\x0ffinalizedHeight\x12\x1a\n" +
	"\bhashrate\x18\x03 \x01(\x04R\bhashrate\x12\x1b\n" +
	"\tis_mining\x18\x04 \x01(\bR\bisMining\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x06 \x01(\rR\tpeerCount\x12\x1e\n" +
	"\n" +
	"difficulty\x18\a \x01(\rR\n" +
	"difficulty\x12#\n" +
	"\roldest_height\x18\b \x01(\x04R\foldestHeight\"S\n" +
	"\x12StartMiningRequest\x12#\n" +
	"\rminer_address\x18\x01 \x01(\tR\fminerAddress\x12\x18\n" +
	"\athreads\x18\x02 \x01(\rR\athreads\"\x13\n" +
	"\x11StopMiningRequest\"D\n" +
	"\x0eMiningResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xec\x01\n" +
	"\n" +
	"WarningMsg\x12<\n" +
	"\x04type\x18\x01 \x01(\x0e2(.btc_genz.network.WarningMsg.WarningTypeR\x04type\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12\x1f\n" +
	"\vreject_hash\x18\x03 \x01(\fR\n" +
	"rejectHash\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"M\n" +
	"\vWarningType\x12\x16\n" +
	"\x12FIREWALL_VIOLATION\x10\x00\x12\x0f\n" +
	"\vINVALID_POW\x10\x01\x12\x15\n" +
	"\x11TIME_WARP_ATTEMPT\x10\x022\xc1\x05\n" +
	"\x11BlockchainService\x12Q\n" +
	"\bGetBlock\x12!.btc_genz.network.GetBlockRequest\x1a\".btc_genz.network.GetBlockResponse\x12c\n" +
	"\x0eGetHeaderBatch\x12'.btc_genz.network.GetHeaderBatchRequest\x1a(.btc_genz.network.GetHeaderBatchResponse\x12M\n" +
	"\x11SubmitTransaction\x12!.btc_genz.transaction.Transaction\x1a\x15.btc_genz.common.Hash\x12T\n" +
	"\tGetStatus\x12\".btc_genz.network.GetStatusRequest\x1a#.btc_genz.network.GetStatusResponse\x12T\n" +
	"\n" +
	"GetAccount\x12#.btc_genz.network.GetAccountRequest\x1a!.btc_genz.network.AccountResponse\x12M\n" +
	"\x18CalculateBlockHeaderHash\x12\x1a.btc_genz.network.RawBytes\x1a\x15.btc_genz.common.Hash\x12U\n" +
	"\vStartMining\x12$.btc_genz.network.StartMiningRequest\x1a .btc_genz.network.MiningResponse\x12S\n" +
	"\n" +
	"StopMining\x12#.btc_genz.network.StopMiningRequest\x1a .btc_genz.network.MiningResponseB\x10Z\x0ebtc_genz/protob\x06proto3"

var (
	file_network_network_proto_rawDescOnce sync.Once
	file_network_network_proto_rawDescData []byte
)

func file_network_network_proto_rawDescGZIP() []byte {
	file_network_network_proto_rawDescOnce.Do(func() {
		file_network_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_network_proto_rawDesc), len(file_network_network_proto_rawDesc)))
	})
	return file_network_network_proto_rawDescData
}

var file_network_network_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_network_network_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_network_network_proto_goTypes = []any{
	(WarningMsg_WarningType)(0),    // 0: btc_genz.network.WarningMsg.WarningType
	(*RawBytes)(nil),               // 1: btc_genz.network.RawBytes
	(*GetAccountRequest)(nil),      // 2: btc_genz.network.GetAccountRequest
	(*AccountResponse)(nil),        // 3: btc_genz.network.AccountResponse
	(*NewBlockMsg)(nil),            // 4: btc_genz.network.NewBlockMsg
	(*NewTxMsg)(nil),               // 5: btc_genz.network.NewTxMsg
	(*InventoryMsg)(nil),           // 6: btc_genz.network.InventoryMsg
	(*GetBlockRequest)(nil),        // 7: btc_genz.network.GetBlockRequest
	(*GetBlockResponse)(nil),       // 8: btc_genz.network.GetBlockResponse
	(*Handshake)(nil),              // 9: btc_genz.network.Handshake
	(*SentinelCertificateMsg)(nil), // 10: btc_genz.network.SentinelCertificateMsg
	(*GetHeaderBatchRequest)(nil),  // 11: btc_genz.network.GetHeaderBatchRequest
	(*GetHeaderBatchResponse)(nil), // 12: btc_genz.network.GetHeaderBatchResponse
	(*GetStatusRequest)(nil),       // 13: btc_genz.network.GetStatusRequest
	(*GetStatusResponse)(nil),      // 14: btc_genz.network.GetStatusResponse
	(*StartMiningRequest)(nil),     // 15: btc_genz.network.StartMiningRequest
	(*StopMiningRequest)(nil),      // 16: btc_genz.network.StopMiningRequest
	(*MiningResponse)(nil),         // 17: btc_genz.network.MiningResponse
	(*WarningMsg)(nil),             // 18: btc_genz.network.WarningMsg
	(*Block)(nil),                  // 19: btc_genz.block.Block
	(*Transaction)(nil),            // 20: btc_genz.transaction.Transaction
	(*Hash)(nil),                   // 21: btc_genz.common.Hash
}
var file_network_network_proto_depIdxs = []int32{
	19, // 0: btc_genz.network.NewBlockMsg.block:type_name -> btc_genz.block.Block
	20, // 1: btc_genz.network.NewTxMsg.tx:type_name -> btc_genz.transaction.Transaction
	19, // 2: btc_genz.network.GetBlockResponse.block:type_name -> btc_genz.block.Block
	0,  // 3: btc_genz.network.WarningMsg.type:type_name -> btc_genz.network.WarningMsg.WarningType
	7,  // 4: btc_genz.network.BlockchainService.GetBlock:input_type -> btc_genz.network.GetBlockRequest
	11, // 5: btc_genz.network.BlockchainService.GetHeaderBatch:input_type -> btc_genz.network.GetHeaderBatchRequest
	20, // 6: btc_genz.network.BlockchainService.SubmitTransaction:input_type -> btc_genz.transaction.Transaction
	13, // 7: btc_genz.network.BlockchainService.GetStatus:input_type -> btc_genz.network.GetStatusRequest
	2,  // 8: btc_genz.network.BlockchainService.GetAccount:input_type -> btc_genz.network.GetAccountRequest
	1,  // 9: btc_genz.network.BlockchainService.CalculateBlockHeaderHash:input_type -> btc_genz.network.RawBytes
	15, // 10: btc_genz.network.BlockchainService.StartMining:input_type -> btc_genz.network.StartMiningRequest
	16, // 11: btc_genz.network.BlockchainService.StopMining:input_type -> btc_genz.network.StopMiningRequest
	8,  // 12: btc_genz.network.BlockchainService.GetBlock:output_type -> btc_genz.network.GetBlockResponse
	12, // 13: btc_genz.network.BlockchainService.GetHeaderBatch:output_type -> btc_genz.network.GetHeaderBatchResponse
	21, // 14: btc_genz.network.BlockchainService.SubmitTransaction:output_type -> btc_genz.common.Hash
	14, // 15: btc_genz.network.BlockchainService.GetStatus:output_type -> btc_genz.network.GetStatusResponse
	3,  // 16: btc_genz.network.BlockchainService.GetAccount:output_type -> btc_genz.network.AccountResponse
	21, // 17: btc_genz.network.BlockchainService.CalculateBlockHeaderHash:output_type -> btc_genz.common.Hash
	17, // 18: btc_genz.network.BlockchainService.StartMining:output_type -> btc_genz.network.MiningResponse
	17, // 19: btc_genz.network.BlockchainService.StopMining:output_type -> btc_genz.network.MiningResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_network_network_proto_init() }
func file_network_network_proto_init() {
	if File_network_network_proto != nil {
		return
	}
	file_block_block_proto_init()
	file_transaction_transaction_proto_init()
	file_common_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_network_proto_rawDesc), len(file_network_network_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_network_proto_goTypes,
		DependencyIndexes: file_network_network_proto_depIdxs,
		EnumInfos:         file_network_network_proto_enumTypes,
		MessageInfos:      file_network_network_proto_msgTypes,
	}.Build()
	File_network_network_proto = out.File
	file_network_network_proto_goTypes = nil
	file_network_network_proto_depIdxs = nil
}
