//*
// @file state.proto
// @brief Định nghĩa cấu trúc Trạng thái (State) BTC GenZ V1.0 Tối Giản.
// @details Quản lý tài khoản theo mô hình Account-based kết hợp Coin ID để nén dữ liệu.
//
// @author Vô Nhật Thiên (Khởi tạo) - BTC GenZ V1.0
// @date 2026-03-24

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: state/state.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Trạng thái Tài khoản (Account State) V1.0
type AccountState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	TotalBtcZ     uint64                 `protobuf:"varint,2,opt,name=total_btc_z,json=totalBtcZ,proto3" json:"total_btc_z,omitempty"` // Tổng số dư BTC_Z (VNT)
	Nonce         uint64                 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`                            // Nonce giao dịch cuối cùng
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountState) Reset() {
	*x = AccountState{}
	mi := &file_state_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountState) ProtoMessage() {}

func (x *AccountState) ProtoReflect() protoreflect.Message {
	mi := &file_state_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountState.ProtoReflect.Descriptor instead.
func (*AccountState) Descriptor() ([]byte, []int) {
	return file_state_state_proto_rawDescGZIP(), []int{0}
}

func (x *AccountState) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *AccountState) GetTotalBtcZ() uint64 {
	if x != nil {
		return x.TotalBtcZ
	}
	return 0
}

func (x *AccountState) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

var File_state_state_proto protoreflect.FileDescriptor

const file_state_state_proto_rawDesc = "" +
	"\n" +
	"\x11state/state.proto\x12\x0ebtc_genz.state\x1a\x13common/common.proto\"~\n" +
	"\fAccountState\x122\n" +
	"\aaddress\x18\x01 \x01(\v2\x18.btc_genz.common.AddressR\aaddress\x12\x1e\n" +
	"\vtotal_btc_z\x18\x02 \x01(\x04R\ttotalBtcZ\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\x04R\x05nonceJ\x04\b\x04\x10\vB\x10Z\x0ebtc_genz/protob\x06proto3"

var (
	file_state_state_proto_rawDescOnce sync.Once
	file_state_state_proto_rawDescData []byte
)

func file_state_state_proto_rawDescGZIP() []byte {
	file_state_state_proto_rawDescOnce.Do(func() {
		file_state_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_state_proto_rawDesc), len(file_state_state_proto_rawDesc)))
	})
	return file_state_state_proto_rawDescData
}

var file_state_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_state_state_proto_goTypes = []any{
	(*AccountState)(nil), // 0: btc_genz.state.AccountState
	(*Address)(nil),      // 1: btc_genz.common.Address
}
var file_state_state_proto_depIdxs = []int32{
	1, // 0: btc_genz.state.AccountState.address:type_name -> btc_genz.common.Address
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_state_state_proto_init() }
func file_state_state_proto_init() {
	if File_state_state_proto != nil {
		return
	}
	file_common_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_state_proto_rawDesc), len(file_state_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_state_proto_goTypes,
		DependencyIndexes: file_state_state_proto_depIdxs,
		MessageInfos:      file_state_state_proto_msgTypes,
	}.Build()
	File_state_state_proto = out.File
	file_state_state_proto_goTypes = nil
	file_state_state_proto_depIdxs = nil
}
