//*
// @file transaction.proto
// @brief Định nghĩa cấu trúc giao dịch BTC GenZ V1.0 Tối Giản.
// @details Loại bỏ hoàn toàn các thực thể phức tạp (M-Coin, Betting, Anonymous).
// Tập trung vào hiệu năng và tính minh bạch tuyệt đối của BTC_Z.
//
// @author Vô Nhật Thiên (Khởi tạo) - BTC GenZ V1.0
// @date 2026-03-24

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: transaction/transaction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Loại tiền tệ duy nhất trong hệ thống V1.0
type CurrencyType int32

const (
	CurrencyType_BTC_Z CurrencyType = 0
)

// Enum value maps for CurrencyType.
var (
	CurrencyType_name = map[int32]string{
		0: "BTC_Z",
	}
	CurrencyType_value = map[string]int32{
		"BTC_Z": 0,
	}
)

func (x CurrencyType) Enum() *CurrencyType {
	p := new(CurrencyType)
	*p = x
	return p
}

func (x CurrencyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CurrencyType) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_transaction_proto_enumTypes[0].Descriptor()
}

func (CurrencyType) Type() protoreflect.EnumType {
	return &file_transaction_transaction_proto_enumTypes[0]
}

func (x CurrencyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CurrencyType.Descriptor instead.
func (CurrencyType) EnumDescriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{0}
}

// Giao dịch chuẩn cho V1.0
type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Sender          *Address               `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver        *Address               `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount          uint64                 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"` // Đơn vị: VNT (1 BTC_Z = 10^8 VNT)
	Fee             uint64                 `protobuf:"varint,5,opt,name=fee,proto3" json:"fee,omitempty"`       // Phí giao dịch cố định/lũy tiến
	Nonce           uint64                 `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`   // Chống replay attack
	Timestamp       uint64                 `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RecentBlockHash []byte                 `protobuf:"bytes,9,opt,name=recent_block_hash,json=recentBlockHash,proto3" json:"recent_block_hash,omitempty"` // Chống Replay Attack sâu
	Signature       *Signature             `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	ChainId         uint64                 `protobuf:"varint,11,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"` // Định danh mạng (Mainnet: 25062025) - Chống Replay Attack
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_transaction_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Transaction) GetSender() *Address {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Transaction) GetReceiver() *Address {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *Transaction) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Transaction) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Transaction) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Transaction) GetRecentBlockHash() []byte {
	if x != nil {
		return x.RecentBlockHash
	}
	return nil
}

func (x *Transaction) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Transaction) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

// Danh sách giao dịch trong một khối 20MB
type TransactionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionList) Reset() {
	*x = TransactionList{}
	mi := &file_transaction_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionList) ProtoMessage() {}

func (x *TransactionList) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionList.ProtoReflect.Descriptor instead.
func (*TransactionList) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionList) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_transaction_transaction_proto protoreflect.FileDescriptor

const file_transaction_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1dtransaction/transaction.proto\x12\x14btc_genz.transaction\x1a\x13common/common.proto\"\xfa\x02\n" +
	"\vTransaction\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x120\n" +
	"\x06sender\x18\x02 \x01(\v2\x18.btc_genz.common.AddressR\x06sender\x124\n" +
	"\breceiver\x18\x03 \x01(\v2\x18.btc_genz.common.AddressR\breceiver\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amount\x12\x10\n" +
	"\x03fee\x18\x05 \x01(\x04R\x03fee\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\x04R\x05nonce\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x04R\ttimestamp\x12*\n" +
	"\x11recent_block_hash\x18\t \x01(\fR\x0frecentBlockHash\x128\n" +
	"\tsignature\x18\n" +
	" \x01(\v2\x1a.btc_genz.common.SignatureR\tsignature\x12\x19\n" +
	"\bchain_id\x18\v \x01(\x04R\achainIdJ\x04\b\a\x10\bJ\x04\b\f\x10\x15\"X\n" +
	"\x0fTransactionList\x12E\n" +
	"\ftransactions\x18\x01 \x03(\v2!.btc_genz.transaction.TransactionR\ftransactions*\x19\n" +
	"\fCurrencyType\x12\t\n" +
	"\x05BTC_Z\x10\x00B\x10Z\x0ebtc_genz/protob\x06proto3"

var (
	file_transaction_transaction_proto_rawDescOnce sync.Once
	file_transaction_transaction_proto_rawDescData []byte
)

func file_transaction_transaction_proto_rawDescGZIP() []byte {
	file_transaction_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_transaction_proto_rawDesc), len(file_transaction_transaction_proto_rawDesc)))
	})
	return file_transaction_transaction_proto_rawDescData
}

var file_transaction_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transaction_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transaction_transaction_proto_goTypes = []any{
	(CurrencyType)(0),       // 0: btc_genz.transaction.CurrencyType
	(*Transaction)(nil),     // 1: btc_genz.transaction.Transaction
	(*TransactionList)(nil), // 2: btc_genz.transaction.TransactionList
	(*Address)(nil),         // 3: btc_genz.common.Address
	(*Signature)(nil),       // 4: btc_genz.common.Signature
}
var file_transaction_transaction_proto_depIdxs = []int32{
	3, // 0: btc_genz.transaction.Transaction.sender:type_name -> btc_genz.common.Address
	3, // 1: btc_genz.transaction.Transaction.receiver:type_name -> btc_genz.common.Address
	4, // 2: btc_genz.transaction.Transaction.signature:type_name -> btc_genz.common.Signature
	1, // 3: btc_genz.transaction.TransactionList.transactions:type_name -> btc_genz.transaction.Transaction
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_transaction_transaction_proto_init() }
func file_transaction_transaction_proto_init() {
	if File_transaction_transaction_proto != nil {
		return
	}
	file_common_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_transaction_proto_rawDesc), len(file_transaction_transaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_transaction_proto_depIdxs,
		EnumInfos:         file_transaction_transaction_proto_enumTypes,
		MessageInfos:      file_transaction_transaction_proto_msgTypes,
	}.Build()
	File_transaction_transaction_proto = out.File
	file_transaction_transaction_proto_goTypes = nil
	file_transaction_transaction_proto_depIdxs = nil
}
