// This file is @generated by prost-build.
/// Tiêu đề khối (Block Header) - Lưu trữ vĩnh viễn
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockHeader {
    #[prost(uint64, tag = "1")]
    pub version: u64,
    #[prost(uint64, tag = "2")]
    pub height: u64,
    #[prost(message, optional, tag = "3")]
    pub parent_hash: ::core::option::Option<super::common::Hash>,
    /// Gốc cây trạng thái (SMT)
    #[prost(message, optional, tag = "4")]
    pub state_root: ::core::option::Option<super::common::Hash>,
    /// Gốc cây giao dịch (Merkle Tree)
    #[prost(message, optional, tag = "5")]
    pub tx_root: ::core::option::Option<super::common::Hash>,
    #[prost(uint64, tag = "6")]
    pub timestamp: u64,
    /// Độ khó mục tiêu (256-bit U256)
    #[prost(bytes = "vec", tag = "7")]
    pub difficulty: ::prost::alloc::vec::Vec<u8>,
    /// Đáp án PoW (Single Winner)
    #[prost(fixed64, tag = "8")]
    pub nonce: u64,
    /// Địa chỉ thợ đào nhận thưởng
    #[prost(message, optional, tag = "9")]
    pub miner_address: ::core::option::Option<super::common::Address>,
    /// \[BATCH 18\] Tổng trọng số tích lũy (u128 - Fork Resolution)
    #[prost(bytes = "vec", tag = "10")]
    pub absolute_weight: ::prost::alloc::vec::Vec<u8>,
    /// \[V1.0.3-GENESIS\] Tuyên ngôn GenZ (Ghi chú lịch sử)
    #[prost(string, tag = "12")]
    pub manifesto: ::prost::alloc::string::String,
}
/// Thân khối (Block Body) - Có thể bị cắt tỉa (Pruning) sau 24h
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockBody {
    #[prost(message, repeated, tag = "1")]
    pub transactions: ::prost::alloc::vec::Vec<super::transaction::Transaction>,
}
/// Cấu trúc Khối đầy đủ
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    #[prost(message, optional, tag = "1")]
    pub header: ::core::option::Option<BlockHeader>,
    #[prost(message, optional, tag = "2")]
    pub body: ::core::option::Option<BlockBody>,
}
/// \[V1.0 FINAL\] Cấu trúc Khối Rút gọn (Compact Block Propagation)
/// Tối ưu hóa lan truyền mạng bằng việc lắp ráp khối tại chỗ (Local Reconstruction).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompactBlock {
    #[prost(message, optional, tag = "1")]
    pub header: ::core::option::Option<BlockHeader>,
    /// Giao dịch thưởng luôn được gửi kèm
    #[prost(message, optional, tag = "2")]
    pub coinbase_tx: ::core::option::Option<super::transaction::Transaction>,
    /// Danh sách ID rút gọn của các tx khác trong Mempool
    #[prost(uint64, repeated, tag = "3")]
    pub short_ids: ::prost::alloc::vec::Vec<u64>,
}
/// Yêu cầu phần giao dịch thiếu hụt khi lắp ráp khối Compact
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBlockTxn {
    #[prost(bytes = "vec", tag = "1")]
    pub block_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, repeated, tag = "2")]
    pub missing_indexes: ::prost::alloc::vec::Vec<u32>,
}
/// Phản hồi các giao dịch thiếu hụt cho Node nhận
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockTxn {
    #[prost(message, repeated, tag = "1")]
    pub transactions: ::prost::alloc::vec::Vec<super::transaction::Transaction>,
}
