// This file is @generated by prost-build.
/// Cấu hình tham số đồng thuận
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConsensusParams {
    #[prost(uint32, tag = "1")]
    pub target_block_time: u32,
    #[prost(uint32, tag = "2")]
    pub difficulty_adjustment_interval: u32,
    #[prost(uint32, tag = "3")]
    pub reward_lockup_period: u32,
    #[prost(uint32, tag = "4")]
    pub mempool_nano_reset_interval: u32,
    #[prost(uint32, tag = "5")]
    pub max_block_size: u32,
}
/// \[ENGINE API V2\] Nhiệm vụ khai thác (Black Box)
/// Go gửi gói này sang Rust để bắt đầu băm mà không cần callback
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MiningTask {
    #[prost(message, optional, tag = "1")]
    pub header: ::core::option::Option<super::block::BlockHeader>,
    #[prost(uint32, tag = "2")]
    pub threads: u32,
    /// 0-100
    #[prost(uint32, tag = "3")]
    pub intensity: u32,
    /// \[V5.3\] Nhận diện phiên từ Go
    #[prost(uint64, tag = "4")]
    pub session_id: u64,
}
/// \[ENGINE API V2\] Kết quả khai thác
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MiningResult {
    #[prost(uint64, tag = "1")]
    pub nonce: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub block_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "3")]
    pub success: bool,
    /// \[V5.3\] Gắn thẻ phiên để tránh "râu ông nọ cắm cằm bà kia"
    #[prost(uint64, tag = "4")]
    pub session_id: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockExecutionRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub block_body_raw: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub miner_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "3")]
    pub height: u64,
    #[prost(uint64, tag = "4")]
    pub nonce: u64,
}
/// \[SYNC-V4\] Giao thức đồng bộ tập trung tại Rust Core
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncChainRequest {
    /// Danh sách các khối liên tiếp nhận được từ mạng
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub blocks_raw: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncInstruction {
    #[prost(enumeration = "sync_instruction::Strategy", tag = "1")]
    pub strategy: i32,
    /// Cao độ bắt đầu tải (nếu lùi)
    #[prost(uint64, tag = "2")]
    pub start_height: u64,
    /// Cao độ kết thúc tải
    #[prost(uint64, tag = "3")]
    pub end_height: u64,
}
/// Nested message and enum types in `SyncInstruction`.
pub mod sync_instruction {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Strategy {
        /// Tiếp tục tải khối tiếp theo
        Continue = 0,
        /// Lùi lại để tìm điểm chung (Healing)
        Backtrack = 1,
        /// Tạm dừng (Chờ Peer hoặc trạng thái khác)
        Stall = 2,
        /// Lỗi nghiêm trọng, cần xóa đệm và làm mới
        DeepRecovery = 3,
    }
    impl Strategy {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Strategy::Continue => "CONTINUE",
                Strategy::Backtrack => "BACKTRACK",
                Strategy::Stall => "STALL",
                Strategy::DeepRecovery => "DEEP_RECOVERY",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "CONTINUE" => Some(Self::Continue),
                "BACKTRACK" => Some(Self::Backtrack),
                "STALL" => Some(Self::Stall),
                "DEEP_RECOVERY" => Some(Self::DeepRecovery),
                _ => None,
            }
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncChainResponse {
    #[prost(enumeration = "sync_chain_response::Status", tag = "1")]
    pub status: i32,
    #[prost(uint64, tag = "2")]
    pub new_height: u64,
    #[prost(uint64, tag = "3")]
    pub fork_point: u64,
    /// Các giao dịch cần trả lại Mempool
    #[prost(bytes = "vec", repeated, tag = "4")]
    pub orphaned_tx_hashes: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Dữ liệu thô để nạp lại Mempool
    #[prost(bytes = "vec", repeated, tag = "6")]
    pub orphaned_txs_raw: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, tag = "5")]
    pub error_msg: ::prost::alloc::string::String,
    /// \[VANGUARD-ORPHAN\] Mã băm của khối cha bị thiếu để Go đi tìm
    #[prost(string, tag = "7")]
    pub missing_parent_hash: ::prost::alloc::string::String,
    /// \[VANGUARD-COMMAND\] Lệnh chiến thuật từ Rust Core
    #[prost(message, optional, tag = "8")]
    pub instruction: ::core::option::Option<SyncInstruction>,
}
/// Nested message and enum types in `SyncChainResponse`.
pub mod sync_chain_response {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Status {
        Accepted = 0,
        ReorgSuccess = 1,
        InvalidChain = 2,
        Orphan = 3,
        /// \[VANGUARD-FIX\] Thêm mã trạng thái cho Lỗi Cục Bộ (DB hỏng/bad sector)
        InternalError = 4,
    }
    impl Status {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Status::Accepted => "ACCEPTED",
                Status::ReorgSuccess => "REORG_SUCCESS",
                Status::InvalidChain => "INVALID_CHAIN",
                Status::Orphan => "ORPHAN",
                Status::InternalError => "INTERNAL_ERROR",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "ACCEPTED" => Some(Self::Accepted),
                "REORG_SUCCESS" => Some(Self::ReorgSuccess),
                "INVALID_CHAIN" => Some(Self::InvalidChain),
                "ORPHAN" => Some(Self::Orphan),
                "INTERNAL_ERROR" => Some(Self::InternalError),
                _ => None,
            }
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeCommand {
    /// Trạng thái Tắt/Bật đào từ giao diện điều khiển
    #[prost(bool, tag = "1")]
    pub is_paused: bool,
    /// Cường độ CPU tối đa (1-100%)
    #[prost(uint32, tag = "2")]
    pub cpu_intensity: u32,
    /// Dữ liệu block header thô cần băm (MiningTask serialized bytes)
    #[prost(bytes = "vec", tag = "3")]
    pub block_template: ::prost::alloc::vec::Vec<u8>,
    /// Độ khó mục tiêu (Target difficulty)
    #[prost(uint64, tag = "4")]
    pub target_difficulty: u64,
    /// ID phiên khai thác hiện tại để phân biệt các block cũ/mới
    #[prost(uint64, tag = "5")]
    pub session_id: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MinerMessage {
    /// Hashrate thực tế (H/s) báo cáo lên UI
    #[prost(uint64, tag = "1")]
    pub current_hashrate: u64,
    /// Nonce kết quả đào được để đóng block
    #[prost(uint64, tag = "2")]
    pub found_nonce: u64,
    /// Hash của block đào được
    #[prost(bytes = "vec", tag = "3")]
    pub block_hash: ::prost::alloc::vec::Vec<u8>,
    /// ID phiên tương ứng của kết quả
    #[prost(uint64, tag = "4")]
    pub session_id: u64,
}
/// Generated client implementations.
pub mod miner_gateway_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct MinerGatewayClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MinerGatewayClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MinerGatewayClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MinerGatewayClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            MinerGatewayClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Luồng gRPC 2 chiều: Miner gửi thông tin lên, Node gửi lệnh xuống
        pub async fn connect_miner(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::MinerMessage>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::NodeCommand>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/btc_genz.consensus.MinerGateway/ConnectMiner",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("btc_genz.consensus.MinerGateway", "ConnectMiner"),
                );
            self.inner.streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod miner_gateway_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MinerGatewayServer.
    #[async_trait]
    pub trait MinerGateway: Send + Sync + 'static {
        /// Server streaming response type for the ConnectMiner method.
        type ConnectMinerStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::NodeCommand, tonic::Status>,
            >
            + Send
            + 'static;
        /// Luồng gRPC 2 chiều: Miner gửi thông tin lên, Node gửi lệnh xuống
        async fn connect_miner(
            &self,
            request: tonic::Request<tonic::Streaming<super::MinerMessage>>,
        ) -> std::result::Result<
            tonic::Response<Self::ConnectMinerStream>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct MinerGatewayServer<T: MinerGateway> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: MinerGateway> MinerGatewayServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MinerGatewayServer<T>
    where
        T: MinerGateway,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/btc_genz.consensus.MinerGateway/ConnectMiner" => {
                    #[allow(non_camel_case_types)]
                    struct ConnectMinerSvc<T: MinerGateway>(pub Arc<T>);
                    impl<
                        T: MinerGateway,
                    > tonic::server::StreamingService<super::MinerMessage>
                    for ConnectMinerSvc<T> {
                        type Response = super::NodeCommand;
                        type ResponseStream = T::ConnectMinerStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::MinerMessage>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MinerGateway>::connect_miner(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ConnectMinerSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: MinerGateway> Clone for MinerGatewayServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: MinerGateway> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: MinerGateway> tonic::server::NamedService for MinerGatewayServer<T> {
        const NAME: &'static str = "btc_genz.consensus.MinerGateway";
    }
}
