// This file is @generated by prost-build.
/// Dòng dữ liệu thô
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RawBytes {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// Yêu cầu lấy trạng thái tài khoản
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAccountRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
}
/// Phản hồi trạng thái tài khoản (S3 Fix)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountResponse {
    #[prost(uint64, tag = "1")]
    pub balance: u64,
    #[prost(uint64, tag = "2")]
    pub nonce: u64,
    #[prost(bytes = "vec", tag = "3")]
    pub address: ::prost::alloc::vec::Vec<u8>,
}
/// Tin nhắn phát sóng Khối mới (Gossipsub)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewBlockMsg {
    #[prost(message, optional, tag = "1")]
    pub block: ::core::option::Option<super::block::Block>,
}
/// Tin nhắn phát sóng Giao dịch mới
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewTxMsg {
    #[prost(message, optional, tag = "1")]
    pub tx: ::core::option::Option<super::transaction::Transaction>,
}
/// \[V1.0 MINIMALIST\] Tin nhắn phát sóng thông báo Khối mới (Inventory)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InventoryMsg {
    #[prost(uint64, tag = "1")]
    pub height: u64,
    #[prost(string, tag = "2")]
    pub hash: ::prost::alloc::string::String,
}
/// Yêu cầu lấy dữ liệu khối theo chiều cao
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBlockRequest {
    #[prost(uint64, tag = "1")]
    pub height: u64,
    /// \[VANGUARD-ORPHAN\] Yêu cầu theo mã băm để giải quyết mồ côi
    #[prost(bytes = "vec", tag = "2")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
}
/// Phản hồi dữ liệu khối
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBlockResponse {
    #[prost(message, optional, tag = "1")]
    pub block: ::core::option::Option<super::block::Block>,
    #[prost(bool, tag = "2")]
    pub found: bool,
}
/// Tin nhắn bắt tay (Handshake)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Handshake {
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub genesis_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "3")]
    pub current_height: u64,
    #[prost(uint64, tag = "4")]
    pub timestamp: u64,
    /// \[V38.2\] Điểm chốt Snapshot gần nhất (Checkpoint)
    #[prost(uint64, tag = "5")]
    pub finalized_height: u64,
    /// \[V38.3\] Khối cũ nhất còn tồn tại trên đĩa (Sau Purge)
    #[prost(uint64, tag = "6")]
    pub oldest_height: u64,
    /// \[NAT-AUDIT\] Trạng thái NAT: 0=Chưa xác định, 1=Public (mở tường lửa), 2=Private (đằng sau NAT)
    #[prost(uint32, tag = "7")]
    pub nat_status: u32,
}
/// \[V4.11\] Tin nhắn Chứng chỉ Vệ binh (Voluntary Sentinel Certificate)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SentinelCertificateMsg {
    /// 32 bytes
    #[prost(bytes = "vec", tag = "1")]
    pub node_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub start_block: u64,
    #[prost(bytes = "vec", tag = "3")]
    pub challenge: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "4")]
    pub t_iterations: u64,
    #[prost(bytes = "vec", tag = "5")]
    pub solution: ::prost::alloc::vec::Vec<u8>,
    /// 64 bytes
    #[prost(bytes = "vec", tag = "6")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
/// \[V5.0\] Yêu cầu lấy hàng loạt Header (Batch Sync)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetHeaderBatchRequest {
    #[prost(uint64, tag = "1")]
    pub start_height: u64,
    #[prost(uint32, tag = "2")]
    pub count: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetHeaderBatchResponse {
    /// Danh sách các Header đã nén (Serialized)
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub headers: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// \[V11.0.3\] Yêu cầu trạng thái Node (S#5 FIX)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetStatusRequest {}
/// \[V11.0.3\] Phản hồi trạng thái Node (S#5 FIX)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetStatusResponse {
    #[prost(uint64, tag = "1")]
    pub current_height: u64,
    #[prost(uint64, tag = "2")]
    pub finalized_height: u64,
    #[prost(uint64, tag = "3")]
    pub hashrate: u64,
    #[prost(bool, tag = "4")]
    pub is_mining: bool,
    #[prost(string, tag = "5")]
    pub version: ::prost::alloc::string::String,
    #[prost(uint32, tag = "6")]
    pub peer_count: u32,
    #[prost(uint32, tag = "7")]
    pub difficulty: u32,
    /// \[V38.3\] Ranh giới dữ liệu thực tế
    #[prost(uint64, tag = "8")]
    pub oldest_height: u64,
}
/// \[MINING\] Yêu cầu bắt đầu đào
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartMiningRequest {
    #[prost(string, tag = "1")]
    pub miner_address: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub threads: u32,
}
/// \[MINING\] Yêu cầu dừng đào
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StopMiningRequest {}
/// \[MINING\] Phản hồi kết quả điều khiển
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MiningResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
