// This file is @generated by prost-build.
/// Giao dịch chuẩn cho V1.0
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(uint64, tag = "1")]
    pub version: u64,
    #[prost(message, optional, tag = "2")]
    pub sender: ::core::option::Option<super::common::Address>,
    #[prost(message, optional, tag = "3")]
    pub receiver: ::core::option::Option<super::common::Address>,
    /// Đơn vị: VNT (1 BTC_Z = 10^8 VNT)
    #[prost(uint64, tag = "4")]
    pub amount: u64,
    /// Phí giao dịch cố định/lũy tiến
    #[prost(uint64, tag = "5")]
    pub fee: u64,
    /// Chống replay attack
    #[prost(uint64, tag = "6")]
    pub nonce: u64,
    #[prost(uint64, tag = "8")]
    pub timestamp: u64,
    /// Chống Replay Attack sâu
    #[prost(bytes = "vec", tag = "9")]
    pub recent_block_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "10")]
    pub signature: ::core::option::Option<super::common::Signature>,
    /// Định danh mạng (Mainnet: 25062025) - Chống Replay Attack
    #[prost(uint64, tag = "11")]
    pub chain_id: u64,
}
/// Danh sách giao dịch trong một khối 20MB
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionList {
    #[prost(message, repeated, tag = "1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
/// Loại tiền tệ duy nhất trong hệ thống V1.0
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CurrencyType {
    BtcZ = 0,
}
impl CurrencyType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            CurrencyType::BtcZ => "BTC_Z",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BTC_Z" => Some(Self::BtcZ),
            _ => None,
        }
    }
}
